config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length:{minimum:10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles=Article.all
  end

  def show
    @articles=Article.find(params[:id])
  end

  def new
    @article=Article.new
  end

  def create
    @article=Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  private
    def article_params
      params.require(:article).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>My Article list</h1>

<ul>
<% @articles.each do |article| %>
    <li>
   <%= link_to article.title, article %>
    </li>
    <%end%>
</ul>
<%= link_to "New Article",new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with model: @article do |form| %>
<div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <%= @article.errors.full_messages_for(:title) do |message| %>
    <div>
    <%= message %>
    </div>
    <% end %>
</div>

<div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <%= @article.errors.full_messages_for(:body).each do |message| %>
    <div>
    <%= message %>
    </div>
    <% end %>
</div>

<div>
    <%= form.submit %>
</div>

<%end%>

app/views/articles/show.html.erb
<h1><%= @articles.title%></h1>
<p><%= @articles.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project01Helloworld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>